name: Run 6.1.0 debug

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js 20
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20.x
#          cache: 'yarn'
#      - name: Enable corepack
#        run: corepack enable
#      - run: yarn install --immutable
#      - run: yarn preversion

#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js 20
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20.x
#          cache: 'yarn'
#      - name: Enable corepack
#        run: corepack enable
#      - run: yarn install --immutable
#        env:
#          YARN_ENABLE_SCRIPTS: false
#      - run: yarn lint
#      - run: yarn build:backend
